cities/urls.py
from django.urls import path

from cities.views import home, CityDetailView, CityCreateView, CityUpdateView, CityDeleteView, CityListView

urlpatterns = [
    # path('', home, name='home'),
    path('', CityListView.as_view(), name='home'),
    path('detail/<int:pk>/', CityDetailView.as_view(), name='detail'),
    path('add/', CityCreateView.as_view(), name='create'),
    path('update/<int:pk>/', CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', CityDeleteView.as_view(), name='delete'),
]

travel/urls.py
from django.contrib import admin
from django.urls import path, include

from routes.views import home, find_routes, add_route, save_route, RouteListView, RouteDetailView, RouteDeleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cities/', include(('cities.urls', 'cities'))),
    path('trains/', include(('trains.urls', 'trains'))),
    path('accounts/', include(('accounts.urls', 'accounts'))),  # отдельное пространство имен у приложенич
    path('', home, name='home'),
    path('find_routes/', find_routes, name='find_routes'),
    path('add_route/', add_route, name='add_route'),
    path('save_route/', save_route, name='save_route'),
    path('list/', RouteListView.as_view(), name='list'),
    path('detail/<int:pk>', RouteDetailView.as_view(), name='detail'),
    path('delete/<int:pk>', RouteDeleteView.as_view(), name='delete'),
    # path('about/', about)
]

routes/models.py
from django.db import models

# Таблицы в БД
from cities.models import City
from trains.models import Train


class Route(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Название маршрута')
    travel_time = models.PositiveSmallIntegerField(verbose_name='Общее время в пути')
    from_city = models.ForeignKey(City, on_delete=models.CASCADE,
                                  related_name='route_from_city_set',
                                  verbose_name='Откуда')
    to_city = models.ForeignKey('cities.City', on_delete=models.CASCADE,
                                  related_name='route_to_city_set',
                                  verbose_name='Куда')
    trains = models.ManyToManyField(Train, verbose_name='Список поездов')  # указания на несколько  записей в одной таблице

    def __str__(self):
        return f'Маршрут № {self.name} из города {self.from_city}'

    class Meta:
        verbose_name = 'Маршрут'
        verbose_name_plural = 'Маршруты'
        ordering = ['travel_time']

templates/about.html
{% extends 'base.html' %}

{% block title %} About {% endblock %}
{% block content %}
     <h1>About {{name}}!</h1>
{% endblock %}

templates/base.html
{% url 'cities:home' as cities_home_url %}
{% url 'cities:create' as cities_create_url %}
{% url 'trains:home' as trains_home_url %}
{% url 'trains:create' as trains_create_url %}
{% url 'home' as home_url %}
{% url 'list' as route_list %}
{% url 'detail' as route_detail %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--      Bootstrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<!--    SELECT2-->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
  <ul class="nav nav-pills ml-auto">
      <li class="nav-item">
        <a class="nav-link
        {% if request.path == home_url %} active {% endif %} " aria-current="page" href="{% url 'home'%}">FindRoute</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.path == cities_home_url %} active {% endif %}" href="{% url 'cities:home'%}">Все города</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.path == trains_home_url %} active {% endif %}" href="{% url 'trains:home'%}">Поезда</a>
      </li>
      <li class="nav-item
        {% if request.path == route_list %} active {% endif %}
        ">
        <a class="nav-link" href="{% url 'list'%}">Маршруты</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle
        {% if request.path == cities_create_url or request.path == trains_create_url %} active {% endif %}"
           data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Добавить</a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item {% if request.path == cities_create_url %} active {% endif %}"
                 href="{% url 'cities:create'%}">Новый город</a></li>
          <li><a class="dropdown-item {% if request.path == trains_create_url %} active {% endif %}"
                 href="{% url 'trains:create'%}">Новый поезд</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item
                {% if request.path == cities_home_url %} active {% endif %}" href="{% url 'cities:home'%}">Все города</a>
          </li>
        </ul>
      </li>
      {% else %}
        <li class="nav-item">
            <a class="nav-link disabled" href=" ">Добавить</a>
        </li>
      {% endif %}
      {% if user.is_authenticated %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout'%}">Выйти</a>
        </li>
      {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login'%}">Войти</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:registration'%}">Регистрация</a>
        </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link disabled">Disabled</a>
      </li>
</ul>

  <div class="container">
      <div class="row">
          <div class="col-md-8 mx-auto my-4">
              {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                              {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% else %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                              {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endif %}
                    {% endfor %}
                </ul>
              {% endif %}
          </div>
      </div>
  </div>

    <div class="container">
        {% block content %} {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script>
      // In your Javascript (external .js resource or <script> tag)
    $(document).ready(function() {
    $('.js-example-basic-single').select2();
    $('.js-example-basic-multiple').select2();
    });
  </script>

  </body>
</html>

templates/form.html
<div class="row">
    <div class="col-md-4">
        <form action="{{ action }}" method="post"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">{{ button }}</button>
</form>
    </div>
</div>

templates/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}
{% block content %}
     <h1>Hello {{name}}!</h1>
{% endblock %}